### PR TITLE
#87 #65 #68 #108 recursive addChild support

### PR DESCRIPTION
**Pull request by kusmierz**

### CODE REVIEW

**Comment by kusmierz** [comment]
Would be awesome to use your fork, but I need this fix also. Could you merge it please?

**Comment by kokspflanze** [comment]
@kusmierz i will check it friday/saturday, atm in vacation, hope this is okay=]

**Comment by kokspflanze** [comment]
@kusmierz i hope you can work, with dev-master, i will work on some more tests for next main version

**Comment by kusmierz** [comment]
Great, thanks @kokspflanze!

**Comment by kusmierz** [comment]
Hm, unfortunately I have to wait for 1.4.x release, as I'm using zf 2.x...

**Comment by kokspflanze** [comment]
i will see what i can do tomorrow for 1.x release with this kind of fix.

have also to create a test for that.

**Comment by kokspflanze** [comment]
@kusmierz check https://github.com/kokspflanze/ZfcTwig/releases/tag/1.4.2

**Comment by kusmierz** [comment]
Thanks. Had some problem with `FlashMessanger` view helper (service alias can't create service), unfortunately it isn't just in-place replacement. Will look at it later.

**Pull request merged**
